import 'package:flutter/material.dart';
import 'package:safe_line/figmaHelpers/svg/svg.dart';

/* Vector Vector 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVector4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 376.5,
      height: 162.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          10.0,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M5 162L5 92.2701L-5 92.2701L-5 162L5 162ZM92.2701 5L151 5L151 -5L92.2701 -5L92.2701 5ZM151 5L254 5L254 -5L151 -5L151 5ZM254 5L315 5L315 -5L254 -5L254 5ZM315 5L376.5 5L376.5 -5L315 -5L315 5ZM45.5627 18.5511C59.5333 9.69955 75.7315 5 92.2701 5L92.2701 -5C73.8364 -5 55.7821 0.238061 40.2106 10.1039L45.5627 18.5511ZM5 92.2701C5 62.3711 20.3063 34.5533 45.5627 18.5511L40.2106 10.1039C12.0602 27.9397 -5 58.9451 -5 92.2701L5 92.2701Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
