// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBOANJTRKfexijLU3ePB16bdG89P8hq-4',
    appId: '1:493243078840:web:d39c9ac5479d57f601fc4d',
    messagingSenderId: '493243078840',
    projectId: 'safeline-775d3',
    authDomain: 'safeline-775d3.firebaseapp.com',
    storageBucket: 'safeline-775d3.appspot.com',
    measurementId: 'G-HBHQKCF19N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3Z4S3pITL81sfweEIFgpmLH5i07hJFc',
    appId: '1:493243078840:android:81526e9124e3d67101fc4d',
    messagingSenderId: '493243078840',
    projectId: 'safeline-775d3',
    storageBucket: 'safeline-775d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_H-5mzxi3nMSCUO4xdcTBn6IqeN3R5_k',
    appId: '1:493243078840:ios:dd179bfad909f6e601fc4d',
    messagingSenderId: '493243078840',
    projectId: 'safeline-775d3',
    storageBucket: 'safeline-775d3.appspot.com',
    iosClientId: '493243078840-mt3vdtiuog5mj7b7fbdl0ri7g5819kta.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeLine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_H-5mzxi3nMSCUO4xdcTBn6IqeN3R5_k',
    appId: '1:493243078840:ios:dd179bfad909f6e601fc4d',
    messagingSenderId: '493243078840',
    projectId: 'safeline-775d3',
    storageBucket: 'safeline-775d3.appspot.com',
    iosClientId: '493243078840-mt3vdtiuog5mj7b7fbdl0ri7g5819kta.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeLine',
  );
}
