import 'package:flutter/material.dart';
import 'package:safe_line/customWidgets/figmaHelpers/svg/svg.dart';

/* Vector Vector 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVector6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 258.5,
      height: 108.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          10.0,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M1.92751 112.614L260.428 4.61353L256.572 -4.61353L-1.92751 103.386L1.92751 112.614Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
