import 'package:flutter/material.dart';

/* Text tagline here ----------
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTaglinehereWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''tagline here ----------''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2102272033691406,
        fontSize: 20.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 94, 78, 228),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
