import 'package:flutter/material.dart';

/* Text SafeLine
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSafeLineWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''SafeLine''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2102272033691406,
        fontSize: 60.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 94, 78, 228),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
