import 'package:flutter/material.dart';
import 'package:safe_line/customWidgets/figmaHelpers/transform/transform.dart';
import 'package:safe_line/customWidgets/figmaHelpers/svg/svg.dart';

/* Ellipse Ellipse 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 0.71,
        b: -0.70,
        c: 0.70,
        d: 0.71,
        child: Container(
          width: 21.9089298248291,
          height: 21.90892791748047,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M21.9089 10.9545C21.9089 17.0044 17.0044 21.9089 10.9545 21.9089C4.90448 21.9089 0 17.0044 0 10.9545C0 4.90448 4.90448 0 10.9545 0C17.0044 0 21.9089 4.90448 21.9089 10.9545Z')
              ..color = Color.fromARGB(255, 94, 78, 228),
          ]),
        ));
  }
}
