import 'package:flutter/material.dart';
import 'package:safe_line/customWidgets/figmaHomeWidgets/GeneratedGroup1Widget.dart';
import 'package:safe_line/customWidgets/figmaHomeWidgets/GeneratedEllipse6Widget.dart';

/* Group Group 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 60.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 60.0,
              height: 60.0,
              child: GeneratedGroup1Widget(),
            ),
            Positioned(
              left: 30.09033203125,
              top: 14.754083633422852,
              right: null,
              bottom: null,
              width: 21.9089298248291,
              height: 21.90892791748047,
              child: GeneratedEllipse6Widget(),
            )
          ]),
    );
  }
}
