import 'package:flutter/material.dart';
import 'package:safe_line/customWidgets/figmaHelpers/transform/transform.dart';
import 'package:safe_line/customWidgets/figmaHelpers/svg/svg.dart';

/* Ellipse Ellipse 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 0.71,
        b: -0.70,
        c: 0.70,
        d: 0.71,
        child: Container(
          width: 42.42852020263672,
          height: 42.42852020263672,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M42.4285 21.2143C42.4285 32.9306 32.9306 42.4285 21.2143 42.4285C9.49795 42.4285 0 32.9306 0 21.2143C0 9.49795 9.49795 0 21.2143 0C32.9306 0 42.4285 9.49795 42.4285 21.2143Z')
              ..color = Color.fromARGB(255, 242, 241, 251),
          ]),
        ));
  }
}
