import 'package:flutter/material.dart';
import 'package:safe_line/customWidgets/figmaHomeWidgets/GeneratedEllipse5Widget.dart';

/* Group Group 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 60.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 29.700439453125,
              top: 9.094947017729282e-13,
              right: null,
              bottom: null,
              width: 42.42852020263672,
              height: 42.42852020263672,
              child: GeneratedEllipse5Widget(),
            )
          ]),
    );
  }
}
